### ISSUE TITLE
Allow a user to provide custom keys and certificates for a manufacturing server

### ISSUE THREAD

**Issue by empovit** [ansible-collections/community.fdo#16]
##### SUMMARY
It is currently not possible to provide keys and certificates to a manufacturing server as they are generated as part of the setup role. 
This means that:
1. There is no way to use custom keys and certificates, e.g. based on a corporate CA. 
2. The manufacturing server knows the owner's private key (or rather owns it). It looks like FDO was meant for use cases when the manufacturing and the owner are separate entities, especially when considering the late binding feature.

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME
roles/setup_manufacturing_server

##### ADDITIONAL INFORMATION

The role should be able receive a directory that contains just the keys and certificates a manufacturing server requires. 
* diun_key.der
* diun_cert.pem
* manufacturer_cert.pem
* manufacturer_key.der
* owner_cert.pem
* device_ca_key.der
* device_ca_cert.pem

Where _owner\_cert.pem_ may originate at a device's prospective owner - not the manufacturer.
A conditional or a separate role should be used to optionally generate keys and certificates for demo purposes.

```yaml
- hosts: manufacturing_server
  gather_facts: true
  become: true
  vars:
    localhost_manufacturing_server_certs_dir: "{{ playbook_dir }}/fdo_keys"
  roles:
  - setup_manufacturing_server
```
