### ISSUE TITLE
Service info configuration is not customizable

### ISSUE THREAD

**Issue by empovit** [ansible-collections/community.fdo#24]
##### SUMMARY
It is not possible to define custom steps for device onboarding under `service_info` as the template has hard-coded steps

- Forces creating an initial user whereas this step is optional
- Allows one and only one file, and doesn't allow setting file permissions
- Doesn't allow setting `additional_serviceinfo`
- Doesn't allow to accommodate additions to the service info configuration, e.g. the new `after_onboarding_reboot` parameter
- Doesn't allow customizing `diskencryption_clevis`
- The only command possible is `touch`

The AOI configuration is better, but can be improved to allow more flexibility forward compatibilitiy.

##### ISSUE TYPE
- Bug Report

##### COMPONENT NAME
roles/configure_aio_server
roles/configure_owner_server

##### ANSIBLE VERSION
```paste below
ansible [core 2.14.0]
  config file = None
  configured module search path = ['/home/vit/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /home/vit/.local/lib/python3.10/site-packages/ansible
  ansible collection location = /home/vit/.ansible/collections:/usr/share/ansible/collections
  executable location = /home/vit/.local/bin/ansible
  python version = 3.10.10 (main, Feb  8 2023, 00:00:00) [GCC 12.2.1 20221121 (Red Hat 12.2.1-4)] (/usr/local/bin/python)
  jinja version = 3.0.3
  libyaml = True
```

##### COLLECTION VERSION
```paste below
Collection    Version
------------- -------
community.fdo 2.0.0
```

##### CONFIGURATION
```paste below
CONFIG_FILE() = None
```

##### OS / ENVIRONMENT
Fedora, installing FDO on RHEL/Rocky

##### STEPS TO REPRODUCE
Try to customize the ServiceInfo-api server when using the `configure_owner_server` role.

```yaml
- name: Set up owner server
  hosts: owner_server
  become: true
  gather_facts: true
  roles:
    - community.fdo.setup_owner_server
    - community.fdo.configure_owner_server
```

The template ()

```yaml
service_info:
  initial_user:
    username: {{ serviceinfo_api_server_service_info_initial_user_username }}
{% if serviceinfo_api_server_service_info_initial_user_password is not none %}
    password: {{ serviceinfo_api_server_service_info_initial_user_password }}
{% endif %}
{% if serviceinfo_api_server_service_info_initial_user_sshkeys is not none %}
    sshkeys:
    - {{ serviceinfo_api_server_service_info_initial_user_sshkeys }}
{% endif %}
  files:
  - path: {{ serviceinfo_api_server_service_files_path }}
    source_path: {{ serviceinfo_api_server_service_files_source_path }}
  commands:
  - command: touch
    args:
    - {{ serviceinfo_api_server_test_path }}
    return_stdout: true
    return_stderr: true
  diskencryption_clevis:
  - disk_label: {{ serviceinfo_api_server_diskencryption_clevis_disk_label }}
    binding:
      pin: tpm2
      config: "{}"
    reencrypt: true
  additional_serviceinfo: ~
```

##### EXPECTED RESULTS
A user can fully customize their serviceinfo-api sequence within the limits of the [FDO implementation](https://github.com/fedora-iot/fido-device-onboard-rs/).

##### ACTUAL RESULTS
Customization is very limited, it is not possible to run even a simple command.
